"""Parser that applies LLM-generated learned regex patterns for known senders."""

import logging
import re
from datetime import date, datetime
from typing import Optional

from email_worker.parsers.base import BaseEmailParser, ParsedEmailTransaction

log = logging.getLogger("email_worker.parsers.learned")


class LearnedRegexParser(BaseEmailParser):
    """Applies regex patterns previously generated by GenericOllamaParser.

    Runs before the generic LLM fallback — gives fast deterministic extraction
    once the LLM has learned a sender's email format at least once.
    """

    def can_parse(self, sender: str, subject: str, body_text: str) -> bool:
        from email_worker.learned_patterns import get_patterns

        return get_patterns(sender) is not None

    def parse(self, sender: str, subject: str, body_text: str, body_html: str) -> list[ParsedEmailTransaction]:
        from email_worker.learned_patterns import get_patterns, increment_hit

        patterns = get_patterns(sender)
        if not patterns:
            return []

        results = []
        for ap in patterns.get("amount_patterns", []):
            try:
                m = re.search(ap["pattern"], body_text, re.IGNORECASE)
                if not m:
                    continue
                raw_amount = m.group(ap.get("group", 1))
                amount = self._clean_amount(raw_amount)
                if not amount:
                    continue

                tx_type = ap.get("tx_type", "expense")
                if tx_type == "detect":
                    tx_type = _detect_type(body_text, patterns.get("type_detect", {}))

                tx_date = _extract_date(body_text, patterns.get("date_pattern"))
                desc = _extract_desc(body_text, patterns.get("desc_pattern")) or subject

                results.append(
                    ParsedEmailTransaction(
                        date=tx_date,
                        amount=amount,
                        tx_type=tx_type,
                        description=desc,
                        confidence=0.82,
                        category_hint="Others",
                    )
                )
            except Exception as exc:
                log.debug("Learned pattern failed for %s: %s", ap, exc)

        if results:
            increment_hit(sender)
            log.info(
                "LearnedRegexParser: %d transaction(s) from sender domain %s",
                len(results),
                sender,
            )
        return results


def _detect_type(text: str, type_detect: dict) -> str:
    text_lower = text.lower()
    for kw in type_detect.get("income_keywords", []):
        if kw.lower() in text_lower:
            return "income"
    return "expense"


def _extract_date(text: str, date_pattern: Optional[dict]) -> date:
    if date_pattern:
        try:
            m = re.search(date_pattern["pattern"], text, re.IGNORECASE)
            if m:
                raw = m.group(date_pattern.get("group", 1))
                fmt = date_pattern.get("format", "%d/%m/%Y")
                return datetime.strptime(raw, fmt).date()
        except Exception:
            pass
    return datetime.now().date()


def _extract_desc(text: str, desc_pattern: Optional[dict]) -> Optional[str]:
    if not desc_pattern:
        return None
    try:
        m = re.search(desc_pattern["pattern"], text, re.IGNORECASE | re.DOTALL)
        if m:
            return m.group(desc_pattern.get("group", 1)).strip()[:200]
    except Exception:
        pass
    return None
