name: Feature request
description: Suggest an idea for Carange
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or pain point.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
